version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${RELATIONAL_DB_USER}
      POSTGRES_PASSWORD: ${RELATIONAL_DB_PASSWORD}
      POSTGRES_DB: ${RELATIONAL_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - cdc-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - cdc-network

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - cdc-network

networks:
  cdc-network:
    driver: bridge

volumes:
  pg-data:
  redis-data:
